"""initial schema

Revision ID: 2fc48b5a4417
Revises: 
Create Date: 2026-09-01 18:22:14.810788

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_shows_status_section', 'shows', ['status', 'section'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('publish_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('catalog_key', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_publish_runs_started_at', 'publish_runs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'season_number', name='uq_seasons_show_number')
    )
    op.create_table('catalog_pointer',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('current_run_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_catalog_pointer_singleton'),
    sa.ForeignKeyConstraint(['current_run_id'], ['publish_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('content_group', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_group', 'language', name='uq_episodes_group_language')
    )
    op.create_index('ix_episodes_content_group', 'episodes', ['content_group'], unique=False)
    op.create_index('ix_episodes_season_number', 'episodes', ['season_id', 'episode_number'], unique=False)
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(show_id, episode_id) = 1', name='ck_artwork_exactly_one_owner'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_artwork_episode_kind', 'artwork', ['episode_id', 'kind'], unique=True, postgresql_where=sa.text('episode_id IS NOT NULL'))
    op.create_index('uq_artwork_show_kind', 'artwork', ['show_id', 'kind'], unique=True, postgresql_where=sa.text('show_id IS NOT NULL'))
    # ### end Alembic commands ###

    # GIN on categories serves the category filter, which uses @>.
    op.create_index(
        'ix_shows_categories_gin', 'shows', ['categories'], unique=False, postgresql_using='gin'
    )
    # The pointer table holds exactly one row for the lifetime of the system.
    op.execute("INSERT INTO catalog_pointer (id, current_run_id) VALUES (1, NULL)")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_shows_categories_gin', table_name='shows', postgresql_using='gin')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_artwork_show_kind', table_name='artwork', postgresql_where=sa.text('show_id IS NOT NULL'))
    op.drop_index('uq_artwork_episode_kind', table_name='artwork', postgresql_where=sa.text('episode_id IS NOT NULL'))
    op.drop_table('artwork')
    op.drop_index('ix_episodes_season_number', table_name='episodes')
    op.drop_index('ix_episodes_content_group', table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('catalog_pointer')
    op.drop_table('seasons')
    op.drop_index('ix_publish_runs_started_at', table_name='publish_runs')
    op.drop_table('publish_runs')
    op.drop_table('users')
    op.drop_index('ix_shows_status_section', table_name='shows')
    op.drop_table('shows')
    op.drop_table('import_issues')
    # ### end Alembic commands ###
